#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="${GPA_KITTY_PLUGIN_DIR:-$HOME/.config/kitty/global-pet-assistant}"
KITTY_CONFIG_DIR="${GPA_KITTY_CONFIG_DIR:-$HOME/.config/kitty}"
KITTY_CONF="${GPA_KITTY_CONF:-$KITTY_CONFIG_DIR/kitty.conf}"
ZSHRC="${GPA_KITTY_PLUGIN_ZSHRC:-$HOME/.zshrc}"
ENV_FILE="$INSTALL_DIR/env.zsh"
KITTY_PLUGIN_CONF="$INSTALL_DIR/kitty.conf"
CONTROL_SOCKET="${GPA_KITTY_CONTROL_SOCKET:-$INSTALL_DIR/kitty.sock}"
CONTROL_ENDPOINT="${GPA_KITTY_CONTROL_ENDPOINT:-unix:$CONTROL_SOCKET}"
MARKER_BEGIN="# >>> global-pet-assistant kitty plugin >>>"
MARKER_END="# <<< global-pet-assistant kitty plugin <<<"
KITTY_MARKER_BEGIN="# >>> global-pet-assistant kitty remote control >>>"
KITTY_MARKER_END="# <<< global-pet-assistant kitty remote control <<<"

replace_block() {
  local file="$1"
  local begin="$2"
  local end="$3"
  local body_file="$4"
  local tmp_file
  tmp_file="$(mktemp)"

  awk -v begin="$begin" -v end="$end" -v body_file="$body_file" '
    function print_body() {
      while ((getline line < body_file) > 0) {
        print line
      }
      close(body_file)
    }
    $0 == begin {
      if (!printed) {
        print_body()
        printed = 1
      }
      skipping = 1
      next
    }
    $0 == end {
      skipping = 0
      next
    }
    !skipping {
      print
    }
    END {
      if (!printed) {
        print ""
        print_body()
      }
    }
  ' "$file" > "$tmp_file"
  mv "$tmp_file" "$file"
}

mkdir -p "$INSTALL_DIR"
mkdir -p "$KITTY_CONFIG_DIR"
install -m 0755 "$SCRIPT_DIR/global_pet_assistant.py" "$INSTALL_DIR/global_pet_assistant.py"
install -m 0644 "$SCRIPT_DIR/shell-integration.zsh" "$INSTALL_DIR/shell-integration.zsh"

echo "Installed Global Pet Assistant kitty plugin to $INSTALL_DIR"

cat > "$ENV_FILE" <<EOF
# Generated by Global Pet Assistant kitty plugin installer.
export GPA_KITTY_PLUGIN_EMITTER="$INSTALL_DIR/global_pet_assistant.py"
export GPA_TERMINAL_PLUGIN_ENDPOINT="\${GPA_TERMINAL_PLUGIN_ENDPOINT:-http://127.0.0.1:17321/terminal-plugin/events}"
export GPA_KITTY_CONTROL_ENDPOINT="\${GPA_KITTY_CONTROL_ENDPOINT:-$CONTROL_ENDPOINT}"
EOF
chmod 0644 "$ENV_FILE"
echo "Installed $ENV_FILE"

if [[ "${GPA_KITTY_PLUGIN_CONFIGURE_KITTY:-1}" != "0" ]]; then
  cat > "$KITTY_PLUGIN_CONF" <<EOF
# Generated by Global Pet Assistant.
# A local Unix socket lets the app send replies back to provider-approved
# sessions that the kitty plugin has observed.
allow_remote_control yes
listen_on $CONTROL_ENDPOINT
EOF
  chmod 0644 "$KITTY_PLUGIN_CONF"

  if [[ ! -f "$KITTY_CONF" ]]; then
    touch "$KITTY_CONF"
  fi

  kitty_block="$(mktemp)"
  {
    printf '%s\n' "$KITTY_MARKER_BEGIN"
    printf 'include %s\n' "$KITTY_PLUGIN_CONF"
    printf '%s\n' "$KITTY_MARKER_END"
  } > "$kitty_block"
  replace_block "$KITTY_CONF" "$KITTY_MARKER_BEGIN" "$KITTY_MARKER_END" "$kitty_block"
  rm -f "$kitty_block"
  echo "Configured kitty remote control include in $KITTY_CONF"
else
  echo "Skipped kitty remote-control configuration because GPA_KITTY_PLUGIN_CONFIGURE_KITTY=0"
  echo "Reply/send-message needs KITTY_LISTEN_ON or GPA_KITTY_CONTROL_ENDPOINT in kitty sessions."
fi

if [[ "${GPA_KITTY_PLUGIN_INSTALL_ZSHRC:-1}" == "0" ]]; then
  echo "Skipped zsh configuration because GPA_KITTY_PLUGIN_INSTALL_ZSHRC=0"
  echo "Enable it manually with:"
  echo "source \"$ENV_FILE\""
  echo "source \"$INSTALL_DIR/shell-integration.zsh\""
  exit 0
fi

if [[ ! -f "$ZSHRC" ]]; then
  touch "$ZSHRC"
fi

zsh_block="$(mktemp)"
{
  printf '%s\n' "$MARKER_BEGIN"
  printf 'if [[ -n "${KITTY_WINDOW_ID:-}" && -r %q ]]; then\n' "$ENV_FILE"
  printf '  source %q\n' "$ENV_FILE"
  printf 'fi\n'
  printf 'if [[ -n "${KITTY_WINDOW_ID:-}" && -r %q ]]; then\n' "$INSTALL_DIR/shell-integration.zsh"
  printf '  source %q\n' "$INSTALL_DIR/shell-integration.zsh"
  printf 'fi\n'
  printf '%s\n' "$MARKER_END"
} > "$zsh_block"
replace_block "$ZSHRC" "$MARKER_BEGIN" "$MARKER_END" "$zsh_block"
rm -f "$zsh_block"
echo "Configured kitty plugin zsh integration in $ZSHRC"

if [[ -z "${GPA_KITTY_PLUGIN_SKIP_PREFLIGHT:-}" ]]; then
  if [[ ! -r "$HOME/.global-pet-assistant/token" ]]; then
    echo "Warning: $HOME/.global-pet-assistant/token was not found. Launch Global Pet Assistant once before verifying events." >&2
  fi
  if command -v curl >/dev/null 2>&1; then
    if ! curl -fsS --max-time 0.5 http://127.0.0.1:17321/healthz >/dev/null 2>&1; then
      echo "Warning: Global Pet Assistant is not reachable on 127.0.0.1:17321 yet." >&2
    fi
  else
    echo "Warning: curl was not found; command flash events cannot be posted from the shell integration." >&2
  fi
fi

echo "Open a new kitty tab/window for command flash."
echo "Fully restart kitty after the first install so kitty loads $KITTY_PLUGIN_CONF for reply/send-message."
